name: lint

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install -U "pre-commit>=3.6.2"
          pre-commit --version
      - name: Run pre-commit
        run: pre-commit run --all-files
